version: '3.4'

services:
    calories:
        ports:
            - 6001:80
        restart: unless-stopped
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
    nutrition:
        ports:
            - 7001:80
        restart: unless-stopped
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
    workouts:
        ports:
            - 8001:80
        restart: unless-stopped
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
    identity:
        ports:
            - 9001:80
        restart: unless-stopped
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
    mongodb:
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=mongo123
        restart: unless-stopped
    redis:
        ports: 
            - 6379:6379
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        restart: unless-stopped